version: "3"
services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: projetocontainer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/projetocontainer?allowPublicKeyRetrieval=true&useSSL=false"
      spring.jpa.hibernate.ddl-auto: "update"
      spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
    depends_on:
      - mysqldb
    restart: "on-failure"


volumes:
  mysqldb: