version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
  mysqldb:
      image: mysql:5.7
      restart: always
      ports:
        - "3307:3306"
      environment:
        MYSQL_DATABASE: projetocontainer
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
