version: "3.8"
services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: projetocontainer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  spring_api:
    container_name: spring_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql_db:3306/projetocontainer?allowPublicKeyRetrieval=true&useSSL=false"
    depends_on:
      - mysql_db
    restart: "on-failure"